#!/usr/bin/env python

## Convert SubtlePatterns site into usable YAML file

import os
import glob
import re
import yaml

from pyquery import PyQuery as Q

BASE_DIR = os.path.dirname(os.path.realpath(__file__))
HTML_PATTERN = os.path.join(BASE_DIR, "html/subtlepatterns_*.html")
YAML_OUTPUT = os.path.join(BASE_DIR, "subtlepatterns.yaml")

print HTML_PATTERN

def get_patterns_from_doc(doc):
    for post in doc("#content .post"):
        qpost = Q(post)
        yield {
            "title": qpost(".entry-title").text(),
            "link": qpost(".entry-title a").attr("href"),
            "download": qpost(".download").attr("href"),
            "description": qpost(".entry-content > p").eq(0).text(),
            "author": re.search("^Made by (.*).", qpost(".entry-content > p").eq(1).html()).groups()[0],
            "image": os.path.basename(re.search("background\-image: url\('?(.*?)'?\)", qpost(".patternpreview").attr("style")).groups()[0]),
        }

def get_patterns_from_filename(filename):
    with open(filename) as file:
        return get_patterns_from_doc(Q(unicode(file.read().decode("utf8"))))

patterns = []

for filename in glob.glob(HTML_PATTERN):
    for pattern in get_patterns_from_filename(filename):
        print "Adding pattern", pattern["title"]
        patterns.append(pattern)

with open(YAML_OUTPUT, "w") as file:
    print "Writing %d patterns" % len(patterns)
    file.write(yaml.safe_dump(patterns, default_flow_style=False))
